# Generated by Django 2.1.4 on 2018-12-26 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTeamOnMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_players', models.ManyToManyField(to='football.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ClaimedTeamOnMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_players', models.ManyToManyField(to='football.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Foul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('goal_type', models.CharField(choices=[('J', 'PENALTY'), ('N', 'FROM_GAME')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='GoalCombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_statistics.Goal')),
                ('participated_players', models.ManyToManyField(to='football.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('viewers', models.IntegerField()),
                ('guest_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_guest_team', to='football.Team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_home_team', to='football.Team')),
                ('line_referee', models.ManyToManyField(related_name='match_line_referee', to='football.Referee')),
                ('main_referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_main_referee', to='football.Referee')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Stadium')),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_statistics.Match'),
        ),
        migrations.AddField(
            model_name='goal',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Player'),
        ),
        migrations.AddField(
            model_name='foul',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_statistics.Match'),
        ),
        migrations.AddField(
            model_name='foul',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Player'),
        ),
        migrations.AddField(
            model_name='claimedteamonmatch',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_statistics.Match'),
        ),
        migrations.AddField(
            model_name='claimedteamonmatch',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Team'),
        ),
        migrations.AddField(
            model_name='change',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_statistics.Match'),
        ),
        migrations.AddField(
            model_name='change',
            name='replaced_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_replaced_from', to='football.Player'),
        ),
        migrations.AddField(
            model_name='change',
            name='replaced_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_replaced_to', to='football.Player'),
        ),
        migrations.AddField(
            model_name='baseteamonmatch',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_statistics.Match'),
        ),
        migrations.AddField(
            model_name='baseteamonmatch',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Team'),
        ),
    ]
