# Generated by Django 2.1.4 on 2018-12-30 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_statistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='time',
        ),
        migrations.RemoveField(
            model_name='foul',
            name='time',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='time',
        ),
        migrations.AddField(
            model_name='change',
            name='minute',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='change',
            name='second',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foul',
            name='minute',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foul',
            name='second',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='minute',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='second',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='main_referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_main_referee', to='football.Referee'),
        ),
        migrations.AlterField(
            model_name='match',
            name='viewers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
