# Generated by Django 2.1.4 on 2019-01-03 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTeamOnMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField()),
                ('second', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Foul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField()),
                ('second', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField()),
                ('second', models.IntegerField()),
                ('goal_type', models.CharField(choices=[('J', 'PENALTY'), ('N', 'FROM_GAME')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='GoalCombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Goal')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('viewers', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('role', models.CharField(choices=[('V', 'GOALKEEPER'), ('A', 'DEFENDER'), ('U', 'FORWARD')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='guest_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_guest_team', to='football.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_home_team', to='football.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='line_referee',
            field=models.ManyToManyField(related_name='match_line_referee', to='football.Referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='main_referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_main_referee', to='football.Referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Stadium'),
        ),
        migrations.AddField(
            model_name='goalcombination',
            name='participated_players',
            field=models.ManyToManyField(to='football.Player'),
        ),
        migrations.AddField(
            model_name='goal',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Match'),
        ),
        migrations.AddField(
            model_name='goal',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Player'),
        ),
        migrations.AddField(
            model_name='foul',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Match'),
        ),
        migrations.AddField(
            model_name='foul',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Player'),
        ),
        migrations.AddField(
            model_name='change',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Match'),
        ),
        migrations.AddField(
            model_name='change',
            name='replaced_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_replaced_from', to='football.Player'),
        ),
        migrations.AddField(
            model_name='change',
            name='replaced_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_replaced_to', to='football.Player'),
        ),
        migrations.AddField(
            model_name='baseteamonmatch',
            name='base_players',
            field=models.ManyToManyField(to='football.Player'),
        ),
        migrations.AddField(
            model_name='baseteamonmatch',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Match'),
        ),
        migrations.AddField(
            model_name='baseteamonmatch',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Team'),
        ),
    ]
